### PR TITLE
Add Server-Side-Request-Forgery category + new additions

### PR DESCRIPTION
**Pull request by euphrat1ca**
hey man i am so excited what u did. 
and now i had pull requests some burp extensions, such as the chunked-coding-converter

### CODE REVIEW

**Comment by snoopysecurity** [comment]
🎉🎉 thanks for contributing! There is one typo in your PR. I've left a comment, please fix that and I will merge 😊

**Comment by euphrat1ca** [comment]
oh that is my mistake.i had change the typo

**Comment by bytebutcher** [comment]
SSRFmap looks like a really nice tool. But it does not seem to be a burp-extension?

**Comment by euphrat1ca** [comment]
> SSRFmap looks like a really nice tool. But it does not seem to be a burp-extension?

SSRFmap takes a Burp request file as input and a parameter to fuzz.

**Comment by snoopysecurity** [comment]
hmm actually @bytebutcher is correct. This repository only contains Burp extensions, not other tools which might parse Burp related data. The rest of the tools you mentioned are Burp extensions. Can you please remove SSRFMap? Thanks.

**Comment by euphrat1ca** [comment]
> hmm actually @bytebutcher is correct. This repository only contains Burp extensions, not other tools which might parse Burp related data. The rest of the tools you mentioned are Burp extensions. Can you please remove SSRFMap? Thanks.

already done

**Comment by snoopysecurity** [comment]
Merged! Thanks for you contribution 🎈🎉

**Pull request merged**
